### ISSUE TITLE
FR: Ideas for scaling improvements 

### ISSUE THREAD

**Issue by lorensr** [zeroasterisk/Meteor-Throttle#11]
1. Allow use of redis instead of MongoDB
2. Provide alternate method of storing in MongoDB, keeping a single row and incrementing a `count` instead of `count` number of rows. Changes throttle algorithm from continuous timing to blocks of time, but that's still accurate enough to be useful in many cases.
3. Use a capped collection:
```
var coll = new Meteor.Collection("myCollection");
coll._createCappedCollection(numBytes);
```

**Comment by zeroasterisk** [comment]
1. Redis vs Mongo is a great idea... and perhaps it's a matter of allowing more customization of the backend collection... NOTE that Redis is super fast if you know the key you want to check, but kinda slow if you need to search through multiple keys, since it's always a full key list.
2. An interesting idea, and one that dovetails nicely with point 1.  Perhaps it would be `key, expire, count` and anything before expire would add??... this would really not be reliable, easy to "fool", but I admit, it would be a lot more performant... I'd have to think about this.  The other option would be to use `setTimeout()` when adding, to then remove... a lot less work on Mongo, and a lot more work on Node.  No idea if that would be a net improvement or not.
3. I don't know what value to make this... perhaps again, just exposing the collection, so you could do whatever config you want...?

**Comment by lorensr** [comment]
- 2. With a limit of X times in Y time: even if fooled, you can at most do 2X a window of Y. And on average over time, you can at most do X.
- 3. Yeah, could be simple as mentioning option to do so in README.

Also, just found out MDG made a rate limiter:

https://github.com/meteor/meteor/pull/4675

but doesn't work across servers:

https://github.com/meteor/meteor/issues/4714

**Comment by zeroasterisk** [comment]
@lorensr would you mind taking a look at the [dev] branch? 

My last commit should make this a lot easier... `setCollection()` now allows you to pass in ANY collection you want, and `getCollection()` gives you easy access to it.

**Comment by lorensr** [comment]
Looks good, thanks! Funny that in-memory is slower due to no index :)

**Comment by zeroasterisk** [comment]
I don't know that it's *always* slower, but that I've seen some profiling which shows it to be... I think YMMV (I have made the wording on that comment less forceful).

Merged, and new version deployed.... let me know how it goes!
