### ISSUE TITLE
Why persist to a collection?

### ISSUE THREAD

**Issue by RobertLowe** [zeroasterisk/Meteor-Throttle#3]
You could probably do:

    Throttle = new Meteor.Collection('throttles', {connection: null});

And save mongo the hit

Cheers

**Comment by zeroasterisk** [comment]
That sounds like a great idea, but I don't think it would work for any multi-app-server system... that is, if you have N Meteor application servers, where N > 1, you rely on MongoDB to keep them in sync, so that throttling would be reliable across them.

Perhaps, though, we could have a configuration option which allowed you to setup the options passed into the collection, to be whatever you want, and perhaps we have an easy config for `connection:null`

Do you want to draft up a fork/pull-request for that Configuration option?

**Comment by RobertLowe** [comment]
@zeroasterisk that's a very valid point I didn't think of; it would be useful as a configuration. If I thought of that point I wouldn't of suggested the change.

**Comment by ononos** [comment]
Find/count is not cheap for pure js mongo for large data, I think instead of minimongo, better use some memcache technique (or just object key-value) if you need not persist.

**Comment by zeroasterisk** [comment]
Yes - it is probably worthwhile to make a configuration which would toggle the collection object to be mongo based or non-mongo based....

**Comment by zeroasterisk** [comment]
I created a [dev] branch and pushed up a possible solution.  

Would you mind testing this for me?

```
cd app
mkdir packages
git clone https://github.com/zeroasterisk/Meteor-Throttle.git 'packages/zeroasterisk:throttle'
cd 'packages/zeroasterisk:throttle'
git checkout dev
git pull
cd ../..
meteor
```

Maybe add a few more unit tests to demonstrate functionality??

Maybe setup a multi-app meteor application and test it out for me and ensure there's a throttle sync?

**Comment by osv** [comment]
I think default must be mongoDB
```js
isCollectionMongo = true;
```
For back compatible behavior.

**Comment by zeroasterisk** [comment]
take a look at an update I just pushed up, with tiny tests, and a most consistent config... feelin pretty good about it.

**Comment by zeroasterisk** [comment]
So you *can* now config with `setCollection(null)` but as you can see in my comments, readme, and the linked PR #10 the profiling on that is much worse than using MongoDB... unless MongoDB is really your bottleneck, you should stick with a "real" collection.

https://github.com/zeroasterisk/Meteor-Throttle/commit/a55e45b34e6696965d5599838dae22de486795f0
